name: Auto Crawl & Upload to Firebase

on:
  schedule:
    - cron: "0 1 * * 0" # Mỗi ngày lúc 03:00 UTC (10:00 sáng giờ VN)
  workflow_dispatch: # Cho phép chạy tay

jobs:
  crawl-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Chrome
        uses: actions/setup-chrome@v1
        with:
          chrome-version: "latest"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler and upload script
        run: |
          python main.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase_key.json
